---
- name: Detect host system architecture
  ansible.builtin.set_fact:
    zot_arch: "{{ zot_arch_table[ansible_architecture].arch }}"

- name: Create system group
  ansible.builtin.group:
    name: "{{ zot_user }}"
    system: true
    state: present

- name: Create system user
  ansible.builtin.user:
    name: "{{ zot_user }}"
    system: true
    shell: /usr/sbin/nologin
    group: "{{ zot_user }}"
    createhome: false

- name: Download zot binary
  ansible.builtin.get_url:
    url: https://github.com/project-zot/zot/releases/download/v{{ zot_registry_version }}/zot-linux-{{ zot_arch }}
    dest: /usr/local/bin/zot
    owner: root
    group: root
    mode: "0755"
  notify: Restart zot

- name: Create zot config folder
  ansible.builtin.file:
    path: /etc/zot
    state: directory
    owner: "{{ zot_user }}"
    group: "{{ zot_group }}"
    mode: "0700"

- name: Create zot storage folder
  ansible.builtin.file:
    path: "{{ zot_registry_config.storage.rootDirectory }}"
    state: directory
    owner: "{{ zot_user }}"
    group: "{{ zot_group }}"
    mode: "0700"
  when:
    - zot_registry_config.storage.rootDirectory is defined

- name: Copy service file
  ansible.builtin.template:
    src: zot.service.j2
    dest: /etc/systemd/system/zot.service
    owner: root
    group: root
    mode: "0600"
  notify: Restart zot

- name: Copy zot config
  ansible.builtin.template:
    src: config.json.j2
    dest: /etc/zot/config.json
    owner: "{{ zot_user }}"
    group: "{{ zot_group }}"
    mode: "0600"
# not working atm: https://github.com/project-zot/zot/issues/2144
#    validate: /usr/local/bin/zot verify %s
  notify: Restart zot

- name: Copy zot htpasswd
  ansible.builtin.template:
    src: htpasswd.j2
    dest: /etc/zot/htpasswd
    owner: "{{ zot_user }}"
    group: "{{ zot_group }}"
    mode: "0600"
  notify: Restart zot

- name: Copy zot credentials
  ansible.builtin.template:
    src: credentials.json.j2
    dest: /etc/zot/credentials.json
    owner: "{{ zot_user }}"
    group: "{{ zot_group }}"
    mode: "0600"
  notify: Restart zot
