- name: create system group
  group:
    name: "{{ zot_user }}"
    system: true
    state: present

- name: create system user
  user:
    name: "{{ zot_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ zot_user }}"
    createhome: false

- name: Download zot binary
  get_url:
    url: https://github.com/project-zot/zot/releases/download/v{{zot_registry_version}}/zot-linux-amd64
    dest: /usr/local/bin/zot
    owner: root
    group: root
    mode: 0755
  notify: restart zot

- name: Create zot config folder
  file:
    path: /etc/zot
    state: directory
    owner: "{{zot_user}}"
    group: "{{zot_group}}"
    mode: 0700

- name: Create zot storage folder
  file:
    path: "{{ zot_registry_config.storage.rootDirectory }}"
    state: directory
    owner: "{{zot_user}}"
    group: "{{zot_group}}"
    mode: 0700
  when:
    - zot_registry_config.storage.rootDirectory is defined

- name: Copy service file
  template:
    src: zot.service.j2
    dest: "/etc/systemd/system/zot.service"
    owner: root
    group: root
    mode: 0600
  notify: restart zot

- name: Copy zot config
  template:
    src: config.json.j2
    dest: "/etc/zot/config.json"
    owner: "{{zot_user}}"
    group: "{{zot_group}}"
    mode: 0600
# not passing for now
#    validate: "/usr/local/bin/zot verify %s"
  notify: restart zot
